# Generated by Django 5.0.7 on 2024-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teachingstaff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='cocurricularaward',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cocurricularaward',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='awards/'),
        ),
    ]
