# Generated by Django 5.0.7 on 2024-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_backgroundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayassignment',
            old_name='grade',
            new_name='FORM',
        ),
        migrations.AddField(
            model_name='administrator',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('deputy_admin', 'Deputy Admin'), ('deputy_academic', 'Deputy Academic')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='title',
            field=models.CharField(choices=[('Mr. ', 'Mr. '), ('Mrs. ', 'Mrs. '), ('Ms. ', 'Ms. ')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('deputy_admin', 'Deputy Admin'), ('deputy_academic', 'Deputy Academic'), ('HOD', 'HOD'), ('HOS', 'HOS'), ('teacher', 'Teacher')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='title',
            field=models.CharField(choices=[('Mr. ', 'Mr. '), ('Mrs. ', 'Mrs. '), ('Ms. ', 'Ms. ')], default=' ', max_length=100),
        ),
    ]
