# Generated by Django 5.0.7 on 2024-08-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_grade_holidayassignment_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
