# Generated by Django 5.0.7 on 2024-08-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayassignment',
            old_name='FORM',
            new_name='grade',
        ),
    ]
